==============================================================================
20230425 15:58:49.143 - INFO - + START SUITE: TEST DEMO [ ]
==============================================================================
20230425 15:58:49.144 - INFO - +- START SETUP: GX1Testlib.Init Test [ ]
20230425 15:58:49.145 - INFO - Loading the project at D:\Workspace\GX1\G1XAutomation\Demo_Auto_Test
20230425 15:58:49.164 - INFO - Squish Hook 192.168.80.130, gx1, C:\Users\xuf\.ssh\bsci
20230425 15:58:49.165 - INFO - Demo_Auto_Test has been loaded successfully
20230425 15:58:49.181 - INFO - connecting to device
20230425 15:58:49.198 - INFO - COM Port COM4 created successfully
20230425 15:58:49.308 - INFO - GX1 Simulator is started
20230425 15:58:51.371 - INFO - found router: gx1.development.squish_server
20230425 15:58:51.371 - FAIL - ConnectionClosedError: receiving: connection lost: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
20230425 15:58:51.381 - DEBUG - Traceback (most recent call last):
  File "D:\Workspace\GX1\G1XAutomation\venv\lib\site-packages\Pyro5\socketutil.py", line 151, in receive_data
    chunk = sock.recv(min(60000, size - msglen))
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Workspace\GX1\G1XAutomation\GX1Testlib.py", line 292, in init_test
    result = self.squish_proxy.connect()
  File "D:\Workspace\GX1\G1XAutomation\squish\squish_proxy.py", line 30, in connect
    return self.proxy.connect()
  File "D:\Workspace\GX1\G1XAutomation\venv\lib\site-packages\Pyro5\client.py", line 510, in __call__
    return self.__send(self.__name, args, kwargs)
  File "D:\Workspace\GX1\G1XAutomation\venv\lib\site-packages\Pyro5\client.py", line 256, in _pyroInvoke
    msg = protocol.recv_stub(self._pyroConnection, [protocol.MSG_RESULT])
  File "D:\Workspace\GX1\G1XAutomation\venv\lib\site-packages\Pyro5\protocol.py", line 189, in recv_stub
    header = connection.recv(6)  # 'PYRO' + 2 bytes protocol version
  File "D:\Workspace\GX1\G1XAutomation\venv\lib\site-packages\Pyro5\socketutil.py", line 435, in recv
    return receive_data(self.sock, size)
  File "D:\Workspace\GX1\G1XAutomation\venv\lib\site-packages\Pyro5\socketutil.py", line 166, in receive_data
    raise ConnectionClosedError("receiving: connection lost: " + str(x))
Pyro5.errors.ConnectionClosedError: receiving: connection lost: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
20230425 15:58:51.381 - INFO - +- END SETUP: GX1Testlib.Init Test (2237)
------------------------------------------------------------------------------
20230425 15:58:51.382 - INFO - +- START TEST: TEST_CASE_1_COMMAND_SIMULATION [ ]
------------------------------------------------------------------------------
20230425 15:58:51.383 - INFO - +- END TEST: TEST_CASE_1_COMMAND_SIMULATION (2)
------------------------------------------------------------------------------
20230425 15:58:51.384 - INFO - +- START TEST: TEST_CASE_2_CLICK_AND_SCREEN_SHOT [ ]
------------------------------------------------------------------------------
20230425 15:58:51.385 - INFO - +- END TEST: TEST_CASE_2_CLICK_AND_SCREEN_SHOT (1)
------------------------------------------------------------------------------
20230425 15:58:51.385 - INFO - +- START TEST: TEST_CASE_3_COMMAND_SEARCH [ ]
------------------------------------------------------------------------------
20230425 15:58:51.386 - INFO - +- END TEST: TEST_CASE_3_COMMAND_SEARCH (1)
------------------------------------------------------------------------------
20230425 15:58:51.386 - INFO - +- START TEST: TEST_CASE_4_TEST_OCR [ ]
------------------------------------------------------------------------------
20230425 15:58:51.387 - INFO - +- END TEST: TEST_CASE_4_TEST_OCR (1)
------------------------------------------------------------------------------
20230425 15:58:51.388 - INFO - +- START TEST: TEST_CASE_5_TEST_COMPARE [ ]
------------------------------------------------------------------------------
20230425 15:58:51.389 - INFO - +- END TEST: TEST_CASE_5_TEST_COMPARE (1)
------------------------------------------------------------------------------
20230425 15:58:51.389 - INFO - +- START TEARDOWN: GX1Testlib.Close Test [ ]
20230425 15:58:52.401 - INFO - disconnecting from device
20230425 15:58:52.417 - INFO - GX1 Simulator is stopped
20230425 15:58:54.452 - FAIL - CommunicationError: cannot connect to ('127.0.0.1', 45082): [WinError 10061] 由于目标计算机积极拒绝，无法连接。
20230425 15:58:54.453 - DEBUG - Traceback (most recent call last):
  File "D:\Workspace\GX1\G1XAutomation\venv\lib\site-packages\Pyro5\client.py", line 310, in connect_and_handshake
    sock = socketutil.create_socket(connect=connect_location,
  File "D:\Workspace\GX1\G1XAutomation\venv\lib\site-packages\Pyro5\socketutil.py", line 283, in create_socket
    sock.connect(connect)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Workspace\GX1\G1XAutomation\GX1Testlib.py", line 320, in close_test
    self.squish_proxy.disconnect()
  File "D:\Workspace\GX1\G1XAutomation\squish\squish_proxy.py", line 33, in disconnect
    return self.proxy.disconnect()
  File "D:\Workspace\GX1\G1XAutomation\venv\lib\site-packages\Pyro5\client.py", line 510, in __call__
    return self.__send(self.__name, args, kwargs)
  File "D:\Workspace\GX1\G1XAutomation\venv\lib\site-packages\Pyro5\client.py", line 234, in _pyroInvoke
    self.__pyroCreateConnection()
  File "D:\Workspace\GX1\G1XAutomation\venv\lib\site-packages\Pyro5\client.py", line 376, in __pyroCreateConnection
    connect_and_handshake(conn)
  File "D:\Workspace\GX1\G1XAutomation\venv\lib\site-packages\Pyro5\client.py", line 336, in connect_and_handshake
    raise errors.CommunicationError(err) from x
Pyro5.errors.CommunicationError: cannot connect to ('127.0.0.1', 45082): [WinError 10061] 由于目标计算机积极拒绝，无法连接。
20230425 15:58:54.453 - INFO - +- END TEARDOWN: GX1Testlib.Close Test (3064)
==============================================================================
20230425 15:58:54.454 - INFO - + END SUITE: TEST DEMO (5549)
==============================================================================
